### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by paireks** [seghier/dotbimRH#1]
Hello!

I'm just testing it and it looks great! Here is an example file from Archicad :)
![2023-09-08_19h39_31](https://github.com/seghier/dotbimRH/assets/47977819/c543e4ea-63f2-460a-9c7f-2dc014ee3126)

There are few things to consider:
1. At first (because I have installed it in some strange directory) the Newtonsoft dll was missing, so maybe it should be attached as well (probably version > 13.0 will be okay). But that's something to consider, because maybe when it's installed somewhere else it automatically takes Rhino's Newtonsoft dll.
2. To make the import complete I think we should store data here for each element:
![image](https://github.com/seghier/dotbimRH/assets/47977819/ab356516-e1dc-476b-b107-4446f11a60e6)
3. Not sure if it's possible, but maybe it is possible to make it the same or similiar as other existing extensions for other formats:
![image](https://github.com/seghier/dotbimRH/assets/47977819/513b3da0-7c04-4e1f-8a60-f3bc692d0cd1)

by maybe renaming it import_BIM and add some more info in details panel :)

**Comment by seghier** [comment]
Thanks [paireks](https://github.com/paireks)
It's open source and anyone can improve the code and because i need to test the original one from you to understand how the settings works and how i can add them to Rhino
Maybe in separate layers?
I don't know that this dll is necessary: Newtonsoft dll
I will add a note about it in readme file.

**Comment by seghier** [comment]
**by maybe renaming it import_BIM and add some more info in details panel :)**

I will rename it import_DOTBIM because if i am not wrong there are other BIM plugins and maybe use Bim as name
And i already added some details but it looks visual studio don't change the file, i will check this
![image](https://github.com/seghier/dotbimRH/assets/6026588/6bfd44c9-debf-4c76-a3f5-125fddbf1d15)

**Comment by paireks** [comment]
Great!

I think the only thing missing right now are these attributes.
Maybe something in this topic could be helpful to implement it: https://discourse.mcneel.com/t/update-of-the-attributes-user-text-window/101421

**Comment by seghier** [comment]
The plugin now import guid, type and color.
Grasshopper can read these informations using `GetUserStrings `and `GetUserString`
But i need to find a way to add them to Rhino.

![image](https://github.com/seghier/dotbimRH/assets/6026588/d0be488b-aedc-4d53-85a9-1e5362a70958)

**Comment by seghier** [comment]
Done, the solution is simple by using object attributes when add new object to the document:
`doc.Objects.Add(geo, attributes);`
![image](https://github.com/seghier/dotbimRH/assets/6026588/59f7eb0b-13fc-408e-b69f-cad8f72827d8)

**Comment by seghier** [comment]
Thanks [paireks](https://github.com/paireks)
Are these informations enough?
![image](https://github.com/seghier/dotbimRH/assets/6026588/14f368e4-6dd5-4747-97fa-a96dbed52b30)

**Comment by paireks** [comment]
Check out this model as a comparison: https://3dviewer.net/#model=https://raw.githubusercontent.com/paireks/dotbim/master/test/ExampleFiles/TestFilesFromGh/BricksRotated.bim

**Comment by paireks** [comment]
Once you click on these bricks you will see how keys and values looks like, so it will be easy to compare :)

**Comment by paireks** [comment]
You can also check this model for data comparison, as here you will find much more data inside elements :)
https://3dviewer.net/#model=https://raw.githubusercontent.com/paireks/dotbim/master/test/ExampleFiles/TestFilesFromGh/BeamBridgeExample.bim

**Comment by seghier** [comment]
Thank you
wWorks fine now and all informations loaded.
And now we can import the bim file from import menu, also with Grasshopper we can read all informations using mesh GetUserStrings and GetUserString

![image](https://github.com/seghier/dotbimRH/assets/6026588/0957b655-f7d8-4ecd-b529-1b1df20fe8d6)

![image](https://github.com/seghier/dotbimRH/assets/6026588/578f9682-016b-4d7b-8812-570ea3503452)

**Comment by paireks** [comment]
Looks great! I'd love to test it myself after new release :)

**Comment by seghier** [comment]
I update it right now by adding other informations: vector, rotation and mesh id

**Comment by paireks** [comment]
Hey! :)

Let me know if you plan to change something, or you can release an updated version there:
![2023-09-13_21h21_12](https://github.com/seghier/dotbimRH/assets/47977819/50c70223-2e28-485b-8a32-c6bf53cc233f)

Because once you release it I will install updated plugin, test it, and will try to advertise it a bit on McNeel forum and Linkedin.
I find it useful already!

**Comment by seghier** [comment]
Hi @paireks 
I updated it yesterday, the attributes are like in bake component.
You can test it , and in the releases i just replace the files without creating a new release.

I also invite you to test this one:
https://github.com/seghier/dotbim-ifc
![image](https://github.com/seghier/dotbimRH/assets/6026588/9e337781-697b-4cae-82de-ef9e713bd074)

I was thinking about a plugin to import ifc file by running the python code from c# and import the converted one to Rhino,
I don't know if that is useful or not.

**Comment by paireks** [comment]
Oh shit, now I see it :) This is going so fast! Let me download an update, and test first, then we will go further, cause I'd love to discuss .bim <-> .ifc :)

**Comment by seghier** [comment]
Anytime 🙂

**Comment by paireks** [comment]
It looks great, but I think we should put Newtonsoft.dll into the release next to dotbim.dll (similiar to dotbimGH)
Otherwise I encounter an error without any description
Once I add Newtonsoft.dll it's okay
I think you can copy-paste it from dotbimGH, so we will make sure it's the same version

**Comment by paireks** [comment]
![2023-09-13_22h03_08](https://github.com/seghier/dotbimRH/assets/47977819/b0a51e63-d8f7-472f-885d-742593c649e8)

**Comment by seghier** [comment]
> It looks great, but I think we should put Newtonsoft.dll into the release next to dotbim.dll (similiar to dotbimGH) Otherwise I encounter an error without any description Once I add Newtonsoft.dll it's okay I think you can copy-paste it from dotbimGH, so we will make sure it's the same version

Done
I add Newtonsoft.dll from Visual studio.

**Comment by paireks** [comment]
Ok here are some updates:
- I've added dotbimRH to dotbim github
- I've added it on dotbim.net list
- I've posted it on linkedin: https://www.linkedin.com/posts/wojciech-radaczy%C5%84ski-4647221a6_bim-rhino-dotbim-activity-7107824911980634112-Fd4E?utm_source=share&utm_medium=member_desktop
- I've posted it there: https://discourse.mcneel.com/t/new-file-format-dotbim/137629/7
- also I've updated dotbimGH with your bake component both on github and food4rhino :)

**Comment by seghier** [comment]
Thanks :)

**Comment by paireks** [comment]
Regarding .bim <-> .ifc:

- I think having it as a tiny desktop app is cool.
- You can try also to pull my branch to yours (my branch is few commits ahead Dion's currently)
- You can try to do pull request to Dion's branch, but I'm not sure if he has time for looking at it to merge it though.

And regarding IFC plugin for Rhino, there are some things to consider:
- dotbim-ifc uses Python, so it would require Python itself to be somehow taken
- dotbim-ifc uses ifcopenshell, so it would require some dependencies regarding this library
- dotbim-ifc is cool as it takes meshes and data using ifcopenshell and display it (so it can treat Rhino as a simple viewer), but some files miss some data during conversion or try to convert and cannot stop. So on one hand it can be useful for some files, but on other cases it won't help or will lose some data. Personally I don't like software that sometimes works, sometimes doesn't ;)

**Comment by seghier** [comment]
Yes because the conversion uses python it is a little annoying with c#.


> * You can try also to pull my branch to yours (my branch is few commits ahead Dion's currently)

Which branch? i am always get lost in Github :D

**Comment by paireks** [comment]
https://github.com/paireks/dotbim-ifc/tree/main

**Comment by paireks** [comment]
To make something similiar only with C# it should be possible with xbim library (https://github.com/xBimTeam/XbimEssentials)

But I don't know how easy it could be to make such bridge with xbim.

**Comment by seghier** [comment]
Looks like a complex task, maybe in future i will try something.
I will update Rhino plugin with material attribute , to render the right color and transparency with Cycles

Before:
![Screenshot 2023-09-14 095259](https://github.com/seghier/dotbimRH/assets/6026588/80e1d9f7-1a47-4473-a2e6-807677117dd1)

After:
![Screenshot 2023-09-14 122900](https://github.com/seghier/dotbimRH/assets/6026588/f063a9f6-c44e-4c81-af65-0ecd0de0578a)

**Comment by paireks** [comment]
Yes it might be complex.

It looks great with Cycles :) however I have to ask if this change something in existing functionality, or not? If yes, then maybe can it be optional?

**Comment by seghier** [comment]
There is a little problem when the faces have different materials.
I think to add an option in Bake component to let the user choose, if he need the materials.
And keep Rhino plugin as it is.

**Comment by paireks** [comment]
Ok, if this could be an option in component, or even separate component maybe, then that would be great :)

**Comment by paireks** [comment]
I'm closing it as it works really well :)
